#!/bin/bash
LANIP=`/sbin/ifconfig | grep "inet addr" | grep -v "127.0.0.1" | awk '{ print $2 }' | awk -F: '{ print $2 }'`
WANIP=`curl --connect-timeout 60 --silent -0 http://icanhazip.com`

if [ -z "$LANIP" ]; then
LANSTAT="Cannot find LAN IP at this time"
COL=31
else
LANSTAT="OK - IP is ${LANIP}"
COL=32
fi

if [ -z "$WANIP" ]; then
WANSTAT="Cannot find WAN IP at this time"
COL=31
else
WANSTAT="OK - IP is ${WANIP}"
COL=32
fi

echo "$SVRTXT";

echo -e "\E[34;00m\n"; tput sgr0
echo -e "\E[34;40m	 #######                             "; tput sgr0
echo -e "\E[34;40m#    #    #    #    # #####  #      ###### "; tput sgr0
echo -e "\E[34;40m #  #     #    #    # #    # #      #      "; tput sgr0
echo -e "\E[34;40m  ##      #    #    # #    # #      #####  "; tput sgr0
echo -e "\E[34;40m  ##      #    #    # #####  #      #      "; tput sgr0
echo -e "\E[34;40m #  #     #    #    # #      #      #      "; tput sgr0
echo -e "\E[34;40m#    #    #     ####  #      ###### ###### "; tput sgr0
echo -e "\E[34;00m                                           "; tput sgr0
echo -e "\E[34;00m    Lan Status: \E[$COL;40m${LANSTAT}      "; tput sgr0
echo -e "\E[34;00m    Wan Status: \E[$COL;40m${WANSTAT}      "; tput sgr0
echo -e "\E[34;00m\n"; tput sgr0

